### ISSUE TITLE
USER STORY: Site navigation

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/where-next#1]
### User Story:
As a **User**, I can **access a navigation bar on every page** so that **I can easily view desired content**
#

### Acceptance Criteria: 
- The navbar should be clearly visible and consistently available on every page of the website.
- The navbar should provide easy and intuitive access to all major sections of the website.
- It should be designed and positioned to make it easy for users to find and use, without being obtrusive or distracting.
- Clicking on a link will take the user to the corresponding section of the website without delay or confusion.
- It should be optimized for accessibility and usability, with appropriate contrast, font size, and other design elements.
- It should be tested to ensure that it works properly on different devices and screen sizes, including desktop and mobile.

#

### Tasks:
- [x] Create a navbar within Navbar.js 
- [x] Create a secondary SidebarNavigation bar for logged in users 
- [x] Make headings/ icons interactive - style in Navbar.css
   - CSS `:hover`
- [x] Fix navbar into position
     - Use bootstrap classes to make mobile friendly

#
