### ISSUE TITLE
USER STORY: Change password

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/where-next#11]
### User Story:
As a **logged-in User**, I can **change my password** so that **I can keep my account secure**
#

### Acceptance Criteria:
- A user can only change their password if they are authenticated
- A user should receive a notification of a successful password change
- The password field must have validation rules to ensure it meets minimum security requirements (e.g. at least 8 characters, including uppercase and lowercase letters, numbers, and special characters).
- Both password fields must be the same to accept a password change
- A user should be prompted to sign in again after a password change
#

### Tasks: 

- [x] Create a "Change Password" page or component that allows the user to enter their current password and their new password
- [x] Implement validation to ensure that the user's new password meets the minimum requirements
- [x] Implement a "Submit" button that sends the user's current password and new password to the server for validation
- [x] If the submitted passwords are valid, update the user's password in the database
- [x] Display a notification to the user indicating that their password has been changed successfully

#
