### ISSUE TITLE
USER STORY: Update a post 

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/where-next#12]
### User Story:
As a **logged-in User**, I can edit my post so that I can fix or update my existing content
#

### Acceptance Criteria: 
- The user should be able to access the "Edit Post" option from their post or post detail page
- When the user clicks on the "Edit Post" option, they should be directed to a page to edit the content of their post
- The edit post page should contain the current content of the post and allow the user to make changes
- It Should include a "Save" button that allows the user to save their changes to the post.
- If the user makes changes to their post, the updated content should be saved in the database
- If the user does not have permission to edit the post (e.g., not the author), the "Edit Post" option should be disabled or hidden

#

### Tasks:
- [x] Create an "Edit Post" icon and display it only if the user is the author of the post 
- [x] Create PostEditForm.js & copy and paste the code from PostCreateForm.js as it's very similar code
- [x] Adjust naming conventions and add to App.js and import at the top 
- [x] Update PostEditForm to have the prepopulated data - useParams()
- [x] Setup useEffect hook to handle api requests - inside define async handleMount function
- [x] Add ternary to check to see if the logged in user owns the post 
- [x] Make changes to handleSubmit function
- [x] Update submit button to 'save'
- [x] Update & simplify jsx code - remove ternary to display upload icon & remove unused imports

#
