### ISSUE TITLE
USER STORY: Delete a post 

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/where-next#13]
### User Story:
As a **logged in User**, I would like the **ability to delete posts** so that I can **remove any post that I don't want to share**
# 

### Acceptance Criteria:
- Only a logged-in user who is the author of the post has the icon displayed to delete their post
- The user should be able to access the "delete post" icon from their post page or post detail
- When the user clicks on the "delete post" option, a confirmation screen is displayed asking the user to confirm their decision to delete the post
After the user confirms their decision, their post should be permanently deleted and removed from the database
# 

### Tasks:
- [x]  Create a "Delete Post" icon and display it only if the user is the author of the post
- [x] Define a handleDelete async function in Post.js
- [x] Inside a try block, make a delete request to `/posts/${id}/` with the axiosRes instance
- [x] Call goBack() on history to redirect the user
- [x] Log any errors to the console
- [x] Pass the handleDelete function to the PostDropdownBar component
- [x] Destructure the handleDelete prop in  PostDropdownBar.js
- [x] Set the delete items onClick attribute to handleDelete

#
