### ISSUE TITLE
USER STORY: Edit profile

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/where-next#16]
### User Story:
As a **logged-in User**, I would like the ability to **update my profile** so that I can **keep my information up to date**
# 

### Acceptance Criteria:
- An edit icon should be displayed on the logged-in user's profile page and should be easy to navigate and find
- The user should be notified of any errors that occur during the profile update process
- The updated profile information should be saved and immediately reflected across the site
- The user should be able to view their updated profile information on their profile page
- If the user tries to leave a required field blank or enters invalid data, they should be prompted with an error message explaining the issue
- The user should receive a confirmation message that their profile has been successfully updated
# 

### Tasks:
- [ ] Add an edit icon to the `Profile.js` file which is displayed if the user is logged in and is the owner of the profile
- [ ] Create `EditProfile.js` which displays current profile data
- [ ] Add an alert to confirm user profile has been updated

#
