### ISSUE TITLE
USER STORY: Follow a user

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/where-next#17]
### User Story:
As a **logged-in User**, I would like the ability to **follow/unfollow users** so I can **keep track of their content and revisit their profiles easily**
# 

### Acceptance Criteria:
- A "Follow" button should be on the user profile page, which the logged-in user can click to start following that user
- A confirmation message should be displayed, indicating that the user has been followed
- The "Follow" button on the user profile page should change to an "Unfollow" button after the user has been followed
- The logged-in user should be able to click on the name or profile picture of a user they are following to visit their profile page
- The logged-in user should be able to unfollow a user by clicking the "Unfollow" button on the user's profile page
- After the logged-in user unfollows a user, the "Unfollow" button on the user's profile page should change back to a "Follow" button
- If the user being followed deletes their account, the follower's list should be automatically updated to remove that user

# 

### Tasks:

- [x] Create a FollowButton component that displays a "Follow" or "Unfollow" button based on the user's following status
- [x] Implement a async function handleFollow in ProfileDataContext.js
- [x] Set handleFollow as the value for SetProfileDataContext.Provider
- [x] Create followHelper and add to Utils
- [x] Update onClick on ProfilePage.js

#
