### ISSUE TITLE
USER STORY: Create a comment

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/where-next#18]
### User Story: 
As a **logged-in User**, I want to be able to **leave comments on a post**, so that I can **express my opinions or ideas related to the post**
# 

Acceptance Criteria: 
- The "Add Comment" button should be visible to only logged in users
- A comment form should be displayed below a post 
- The comment form should have a "Submit" button to allow the user to submit their comment
- After submitting the comment, it should appear immediately, without requiring the page to be refreshed
- The comment should display the user's name, the date and time it was posted, and the text of the comment
- The comment section should have appropriate moderation features, such as flagging or comment approval

# 

### Tasks: 
- [x] Create comments folder in pages folder with CommentCreateForm.js
- [x] Create CommentCreateForm function which takes in props 
- [x] Add handleSubmt async function
- [x] Add handleChange function
- [x] Back in PostPage.js, import the CommentCreateForm & the useCurrentUser from contexts folder
- [x] Add ternary to the comments section using the CommentCreateForm
- [x] Add and declare any necessary variables

#
