### ISSUE TITLE
USER STORY: Bookmark a post

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/where-next#19]
### User Story: 
As a **logged-in User**, I can **save a post to a personal list** so that I can **easily return to it later**
# 

### Acceptance Criteria: 
- The user should be able to save a post by clicking a bookmark icon below a post
- When the user clicks the "Bookmark" button, the post should be added to a "Bookmarks" list associated with the user's account
- The user should be able to view their list of saved posts on a separate page
- Each saved post in the list should display the post's title, image, description and date published
- The user should be able to remove a saved post from their list by clicking the bookmark icon again
- The user should be notified that they have successfully bookmarked/ removed a post
- The user should not be able to save the same post multiple times to their bookmarks list
# 

### Tasks:
- [x] Create a handeBookmark async function which retrieves the data from the api for bookmarks/
- [x] Import axiosRes - `import { axiosRes } from "../../api/axiosDefaults";`
- [x] Add onClick to span of bookmark outline - `<span onClick={handleBookmark}>`

#
