### ISSUE TITLE
USER STORY: Register for an account

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/where-next#2]
### User Story:
As a **User**, I can **register for an account** so that **I can gain access to all the features that are available exclusively to registered users**
#

### Acceptance Criteria:
- The registration form must include fields for username, password and repeat password.
- Fields must have validation rules to ensure they are unique and in the correct format.
- The password field must have validation rules to ensure it meets minimum security requirements (e.g. at least 8 characters, including uppercase and lowercase letters, numbers, and special characters).
- Once the account is activated, the user should be able to log in and access all the features available to registered users.
- If the user enters invalid information during the registration process, appropriate error messages should be displayed to guide them towards correcting the errors.
- The user should not be able to register again with the same email or username after a successful registration.
 
# 

### Tasks:
- [x] Create a SignUpForm.js
- [x] Use react-bootstrap for a basic form
- [x] style and import css files
- [x] Add event handlers - handleSubmit/handleChange
- [x] Add the route path for /signup as <SignUpForm /> in App.js

#
