### ISSUE TITLE
USER STORY: Like a post 

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/where-next#20]
### User Story:
As a **logged-in User**, I want to **express my appreciation for posts that interest me by liking them**, so that I can **engage with the content and show support for the author**

### Acceptance Criteria:
- The user should be able to like a post by clicking a "Like" button/icon on the post detail page
- The "Like" button should be visible to all users but only logged in users can like a post, prompt for login if not 
- When the user clicks the "Like" button, the post's like count should increment by one
- The user should only be able to like a post once
- The user should be able to unlike a post by clicking the "Unlike" button on the post detail page
- The "Unlike" button should only be visible if the user has already liked the post
- When the user unlikes a post, the post's like count should decrement by one.
- The post's like count should be visible below the post
# 

### Tasks: 
- [x] Create a handeLike async function which retrieves the data from the api for likes/
- [x] Import axiosRes - `import { axiosRes } from "../../api/axiosDefaults";`
- [x] Define `setPosts` in props
- [x] Add onClick to span of heart outline - `<span onClick={handleLike}>`
#
