### ISSUE TITLE
USER STORY: Search for a profile or post

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/where-next#21]
### User Story:
As a **User**, I can **search for posts or profiles by keyword** so that I can **find what I'm looking for more efficiently**
# 

### Acceptance Criteria: 
- The user can enter a keyword in a search bar and see a list of relevant posts or profiles
- The search results should be displayed in a clear and easy-to-read format
- The user should receive appropriate feedback if their search returns no results, such as a message to try a different keyword
# 

### Tasks:
- [x] Within the PostsPage.js file, Add a form component using react-bootstrap
- [x] Inside the form, create a single  Form.Control component, and set its type to text
- [x] To handle the query value, use the useState hook to destructure the query variable and setQuery function
- [x] In the Form.Control component, set its value prop to the ‘query’ variable and update that value in the onChange attribute by calling setQuery with the event target’s value
- [x] Add a new parameter to our API request to include the query  
- [x] Add the query to the useEffect dependency array
#
