### ISSUE TITLE
USER STORY: Delete a comment

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/where-next#23]
### User Story:
As a **logged-in User** who is the **owner of the comment**, I can **delete my comment** so that I can **remove any unwanted comments from the site**
# 

### Acceptance Criteria:
- The user can navigate to their comment and click a "Delete" button
- Upon clicking the "Delete" button, the user should be prompted to confirm that they want to delete the comment
- If the user confirms that they want to delete the comment, the comment should be removed from the site and database
- The comment deletion feature should only be available to the owner of the comment who is logged in
- If the user tries to delete a comment they do not own, they should be shown an error message and prevented from deleting the comment
- If the comment deletion is successful, the user should be shown a success message indicating that the comment has been deleted
# 

### Tasks: 
- [x] Create a UI for displaying a "Delete" button for the comment owner
- [x] Link backend API that can handle comment deletion requests & filter out the deleted comment from the array
- [x] Update setPost and setComments in PostPage.js
- [x] In Comment.js update props with setPost and setComments
- [x] Create handleDelete async function
- [x] Add handleDelete to PostDowndownBar.js - `handleDelete={handleDelete}`

#
