### ISSUE TITLE
USER STORY: Infinite scroll in feed 

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/where-next#26]
### User Story: 
As a **User**, I can keep **scrolling through my feed of posts which load automatically**, so that **I don't have to change pages**
# 

### Acceptance Criteria:
- The feed displays an infinite scroll of posts, with new posts loading automatically as the user scrolls down the page
- The infinite scroll functionality should work correctly across all supported devices
- The site should display an appropriate loading indicator or animation while new posts are being loaded
# 

### Tasks:
- [x] Install react-infinite-scroll-component with `npm install react-infinite-scroll-component`
- [x] Inside our nested ternary in PostsPage.js, we map over our posts, and auto-import the InfiniteScroll component from the library we just installed
- [x] To render our Post components, set a “children” prop and add the array of posts that we are mapping over
- [x] Set the dataLength prop,  which tells the component how many posts are currently being displayed. Set its value to `posts.results.length`
- [x] Set the loader prop and pass it the Asset component with the spinner prop attached
- [x] The hasMore prop will only accept a boolean value  of true or false, so use a logical operator called the double not operator `!!`
- [x] Add a next prop that accepts a function that will be called to load the next page of results  
- [x] Create Utils folder with utils.js file and create a function which passes the 'next' prop
- [x] Go back to PostsPage.js and inside the next prop of the InfiniteScroll component, auto-import  fetchMoreData, and pass it posts and setPosts

# 

#
