### ISSUE TITLE
USER STORY: View a post

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/where-next#4]
### User Story:
As a **user**, I can **view posts**, without **having to sign-up to enjoy the site's content**
#

### Acceptance Criteria:
- Posts should be publicly available and accessible without requiring a user account.
- The user should be able to browse and search the site's content (posts) without being prompted to sign up or log in.
- The user should not encounter any barriers or pop-ups that require them to sign up or sign in to access the site's content.
- The user should be able to access and view any linked media (e.g. images, videos) within the posts without being prompted to sign up or log in.
- If the user attempts to perform an action that requires a user account (e.g. liking, commenting, bookmarking), they should be prompted to sign up or log in to complete the action.
- The user should not be required to provide any personal information or create an account in order to access the site's content.
# 

### Tasks:
- [x] Create a 'Feed' tab in the navigation section of the homepage
- [x] Create Post.js 
- [x] Add Post.js to PostPage.js
- [x] Create Post component
- [x] Define a currentUser variable using the useCurrentUser hook exported from the currentUserContexts file.
