### ISSUE TITLE
USER STORY: Birthday Reminder

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/where-next#44]
### User Story: 
As a **logged-in User**, I want to **receive birthday alerts for my connections**, so that **I can send them a personalized birthday comment**

# 

### Acceptance Criteria:
- The birthday section should be displayed on the logged in users homepage
- It should display the name and profile picture of the user celebrating their birthday
- Users should be able to opt in/out of allowing their date of birth to be shown to their followers

# 

### Tasks: 
- [ ] Create a new section within PostPage.js to display the birthday alerts on the user's homepage - next to `PopularProfiles.js`
- [ ] Implement a function to check for upcoming birthdays using the date of birth field from the Profiles app in the drf api 
- [ ] Link new function page to display within PostPage.js

#
