### ISSUE TITLE
Join/Leave functionality for groups

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/where-next#45]
### User Story:
As a **logged-in User**, I want to be **able to join or leave groups** so that I can **easily manage my membership and participate in groups relevant to me**.
# 

### Acceptance Criteria:
- The user should be able to see a list of groups they are currently a member of from the Group detail page
- The user should be able to join a group and receive a notification when their request has been approved
- A users avatar should be displayed within the GroupDetail page when they have successfully joined the group
- The user should be able to leave a group they are currently a member of and receive a notification when they have left
- ~~The user should be able to search for groups based on keywords or categories and be able to filter search results~~
- ~~Group owners should have the ability to approve or deny membership requests~~
# 

### Tasks:
- [x] Implement the functionality for joining a group and leaving a group within the GroupDetail.js page
- [x] Integrate the backend API with React and ensure that only authenticated users can join or leave groups
- [x] Implement notifications for membership requests, ~~including sending notifications to group admins~~ and users upon approval or denial of membership requests

#
