### ISSUE TITLE
USER STORY: Create a post

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/where-next#5]
### User Story:
As a **logged-in User**, I can **create posts** so that **I can add content to the site**
#

### Acceptance Criteria:
- The logged in user should be able to access a "create post" option from a visible and accessible location within the homepage.
- The "create post" functionality should allow the user to create posts with a title, image and description.
- The "create post" functionality should allow the user to preview their post content before submitting it.
- If the user encounters any errors or issues while creating or submitting a post, the site should provide informative error messages to help the user correct the issue.

# 

### Tasks:
- [ ] Create an 'Add Post' button to a logged in users nav section
- [ ] Create a PostCreateForm.js
- [ ] Link to appropriate pages

#
