### ISSUE TITLE
USER STORY: Login

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/where-next#6]
### User Story:
As a **User**, I can **log into my account** so that **I can access functionality for logged in users**
#

### Acceptance Criteria:
- The user should have a button displayed in the navbar to sign into their account 
- The sign-in button should take the user to a sign-in page
- If user credentials are correct, the user will be signed in
- If user credentials are incorrect, the user will be prompted with an error alert
# 

### Tasks: 
- [x] Create SignInForm.js
- [x] Follow similar structure to SignUpForm.js
- [x] Add event handlers - handleSubmit/handleChange
- [x] Add the route path for /signin in App.js

#
